In [1]:
# Simulating a batch of images: [Batch=10, Channels=3, Height=32, Width=32]
import torch
images = torch.randn(10, 3, 32, 32)

# Swap Channels (dim 1) and Height (dim 2)
swapped = images.transpose(1, 2)

print(swapped.shape)  # torch.Size([10, 32, 3, 32])


torch.Size([10, 32, 3, 32])


In [2]:
images = torch.arange(24).reshape(2, 3, 4)

In [3]:
images

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [4]:
r1 = images.transpose(1, 2)

In [5]:
images

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
r1

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [7]:
r2 = images.transpose(2, 1)

In [8]:
r2

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [9]:
r2 == r1

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]])

In [12]:
torch.allclose(r1, r2)

True