In [3]:
# Simulating a batch of images: [Batch=10, Channels=3, Height=32, Width=32]
import torch
images = torch.randn(10, 3, 32, 32)

# Swap Channels (dim 1) and Height (dim 2)
swapped = images.transpose(1, 2)

print(swapped.shape)  # torch.Size([10, 32, 3, 32])


torch.Size([10, 32, 3, 32])


In [4]:
images = torch.arange(24).reshape(2, 3, 4)

In [5]:
images

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
r1 = images.transpose(1, 2)

In [7]:
images

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
r1

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [9]:
r2 = images.transpose(2, 1)

In [10]:
r2

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [11]:
r2 == r1

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True],
         [True, True, True]]])

In [12]:
torch.allclose(r1, r2)

True

In [16]:
def causal_mask(size):
    mask = torch.triu(torch.ones((1, size, size)), diagonal=1).type(torch.int)
    return mask == 0

In [17]:
causal_mask(3)

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [18]:
def causal_mask_simple(size):
    mask = torch.tril(torch.ones((1, size, size)), diagonal=0).type(torch.int)
    return mask == 1

In [19]:
causal_mask_simple(3)

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [20]:
causal_mask_simple(3) == causal_mask(3)

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]]])

In [21]:
2 ** 32

4294967296

In [22]:
t = torch.arange(12).reshape(1, 3, 4)

In [23]:
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [24]:
t[:, -1]

tensor([[ 8,  9, 10, 11]])

In [25]:
t.shape

torch.Size([1, 3, 4])

In [26]:
t[:, -1]

tensor([[ 8,  9, 10, 11]])

In [27]:
t[:, :, -1]

tensor([[ 3,  7, 11]])

In [28]:
t[:, -1, :]

tensor([[ 8,  9, 10, 11]])

In [29]:
t[:, -1]

tensor([[ 8,  9, 10, 11]])

In [30]:
t[:, -1, :]

tensor([[ 8,  9, 10, 11]])